### ISSUE TITLE
Error/Issue with code for stripping version from ENSEMBL ids

### ISSUE THREAD

**Issue by samuel-marsh** [hbctraining/DGE_workshop#20]
Hi,

I believe there might be an error in the code for stripping version ids from ENSEMBL IDs because some version numbers are double digits. (lesson 9a)

If you apply current code to a file that contains any double digit ensembl version ids (including the demo salmon files):
Current code: `ids.strip <- str_replace(ids, "([.][0-9])", "")`
Then the second number in the ENSEMBL version ID is appended to the end to the ENSEMBL IDs which results in errors in downstream processes.
_ENST00000339924.12
becomes
ENST000003399242
instead of 
ENST00000339924_

Probably a more efficient way to do this but I circumvented this by running two code steps to strip double digit and then single digit version ids:
`ids.strip <- str_replace(ids, "([.][0-9][0-9])", "")`
`ids.strip <- str_replace(ids.strip, "([.][0-9])", "")`

Best,
Sam

**Comment by mistrm82** [comment]
That's a great catch, thanks @samuel-marsh . I didn't realize there were double digit version instances, this has now been incorporated.

In future revisions of this lesson, we are planning to remove annotables and use the ensembldb package instead. This might help avoid having to strip the id versions altogether
