### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by adirot** [hbctraining/DGE_workshop#34]
In https://hbctraining.github.io/DGE_workshop/lessons/04_DGE_DESeq2_analysis.html#:~:text=The%20DESeq2%20dispersion%20estimates%20are,only%20based%20on%20their%20variance

There is a broken link to the 'count normalization' lesson.
I think it should go here: https://github.com/hbctraining/DGE_workshop/blob/master/lessons/02_DGE_count_normalization.md

**Comment by rkhetani** [comment]
@adirot Thanks for pointing that out! We have fixed the link.
